# Generated by Django 5.1.3 on 2024-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_inventario_area_remove_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='estado_general',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='estado_inventario',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='partes_mantenidas',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='software_actualizado',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_inicial',
            field=models.CharField(choices=[('Óptimo', 'Óptimo'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], default='Bueno', max_length=50),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='notas_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='responsable_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='sugerencias_optimizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tareas_realizadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
