# Generated by Django 5.1.3 on 2024-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_mantenimiento_estado_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='detalle_bien',
            field=models.CharField(choices=[('CPU', 'CPU'), ('MONITOR', 'Monitor'), ('LAPTOP', 'Laptop'), ('IMPRESORA', 'Impresora'), ('ALL IN ONE', 'All in One')], max_length=50),
        ),
    ]
