# Generated by Django 5.1.3 on 2024-12-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_mantenimiento_tareas_realizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tareas_otros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
