# Generated by Django 5.1.3 on 2024-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_inventario_capacidad_disco_inventario_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='detalle_bien',
            field=models.CharField(choices=[('CPU', 'CPU'), ('Laptop', 'Laptop'), ('Impresora', 'Impresora'), ('All in One', 'All in One')], max_length=50),
        ),
    ]
