# Generated by Django 5.1.3 on 2024-12-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_area_responsable_alter_inventario_detalle_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='notas_generales',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='sugerencias_optimizacion',
        ),
    ]
