# Generated by Django 5.1.3 on 2024-12-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_mantenimiento_notas_generales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periferico',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='periferico',
            name='area_actual',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perifericos', to='inventario.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periferico',
            name='equipo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perifericos', to='inventario.inventario'),
        ),
    ]
