# Generated by Django 5.1.3 on 2024-12-05 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_periferico_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periferico',
            name='area_actual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perifericos', to='inventario.area'),
        ),
    ]
