# Generated by Django 5.1.3 on 2024-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_periferico_area_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
        migrations.DeleteModel(
            name='RegistroFotografico',
        ),
    ]
