# Generated by Django 5.1.3 on 2024-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_mantenimiento_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='foto_antes',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='foto_despues',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_antes_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_antes_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_despues_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='foto_despues_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento'),
        ),
    ]
