# Generated by Django 5.1.3 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_remove_mantenimiento_foto_antes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_antes_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_antes_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_despues_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_despues_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
    ]
