# Generated by Django 5.1.3 on 2024-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_mantenimiento_foto_antes_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
