# Generated by Django 5.1.3 on 2024-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_alter_mantenimiento_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='procesador',
            field=models.CharField(blank=True, choices=[('Intel Celeron', 'Intel Celeron'), ('Intel Pentium', 'Intel Pentium'), ('Intel Core i3', 'Intel Core i3'), ('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ram',
            field=models.CharField(blank=True, choices=[('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB')], null=True),
        ),
    ]
