# Generated by Django 5.1.3 on 2024-12-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_inventario_procesador_alter_inventario_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='procesador',
            field=models.CharField(blank=True, choices=[('Intel Celeron', 'Intel Celeron'), ('Intel Atom', 'Intel Atom'), ('Intel Pentium', 'Intel Pentium'), ('Intel Core i3', 'Intel Core i3'), ('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ram',
            field=models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB')], null=True),
        ),
    ]
