# Generated by Django 5.1.3 on 2024-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_inventario_procesador_alter_inventario_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='sistema_operativo',
            field=models.CharField(blank=True, choices=[('Win 7', 'Win 7'), ('Win 8.1', 'Win 8.1'), ('Win 10', 'Win 10'), ('Win 11', 'Win 11')], max_length=50, null=True),
        ),
    ]
