# Generated by Django 5.1.3 on 2024-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_alter_inventario_sistema_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='acciones_recomendadas',
            field=models.TextField(blank=True, default='Se recomienda realizar el mantenimiento periódico de cada 2 o 3 meses', null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='problemas_detectados',
            field=models.TextField(blank=True, default='Presencia de polvo en ventiladores y resto del equipo', null=True),
        ),
    ]
